### ISSUE TITLE
Allow passing environment variables from workspace

### ISSUE THREAD

**Issue by mike-oakley** [jimasp/behave-vsc#12]
Hey there!

From what I can tell, the current behaviour is to only pass environment variables specified in `envVarList`. It would be great if this extension could pass through the variables already configured in my shell (so it has the same behaviour as if I called `behave` from the command line myself).

Thanks!

**Comment by jimasp** [comment]
Hi, I'm busy working on changes for the  next  release atm, but I'll take a look when I get a chance.

**Comment by jimasp** [comment]
I've had a quick look. It seems like a simple change, so it should go into the next release. (I'll update this issue to confirm.)

**Comment by mike-oakley** [comment]
Works perfectly - thanks!
