### ISSUE TITLE
"No module named 'features'" for `features` folder that is not in root

### ISSUE THREAD

**Issue by ycsin** [jimasp/behave-vsc#15]
Hi there, my directory structure is similar to the [example-projects](https://github.com/jimasp/behave-vsc/tree/main/example-projects)/[project A](https://github.com/jimasp/behave-vsc/tree/main/example-projects/project%20A)

But my `environment.py` needs to import a python script (i.e. `test_script1.py`) in the same folder as `environment.py`:
```python
from features import test_script1
```

It errors when I run any of the test from the plugin
```
    from features import test_script1
ModuleNotFoundError: No module named 'features'
Exception ModuleNotFoundError: No module named 'features'
```

I also have a folder (i.e. `foobar`) inside the `features` folder that contains multiple python scripts that will be used by the `steps_*.py` inside the `step` folder, which need to import them like so:

```python
from features.foobar.something import *
```

Is such directory structure supported by this plugin? Thanks.

**Comment by jimasp** [comment]
Python errors are usually things like having no `__init__.py` file or vscode using the incorrect python interpreter or virtual environment etc.  

Bear in mind that the extension itself has no knowledge of Python. It is written in TypeScript/Javascript and simply executes Python (using the project folder as the working directory).

If you have errors coming from Python, the first steps to diagnosing the problem would be:
1. Try and run a test
2. Go to the Behave VSC window
3. Run the ouputted commands in that window manually from a terminal (i.e. WITHOUT using the extension). 

Get No. 3 working without the extension. (Note that the python path in the command is set by your vscode python interpreter selection, not the extension.)

**Comment by ycsin** [comment]
@jimasp Thanks for the tips!
