### ISSUE TITLE
Initial release?

### ISSUE THREAD

**Issue by mike-oakley** [jimasp/behave-vsc#18]
Hey!

Loving this extension. Could you cut a non-prerelease version so I can set it to be installed by default in devcontainers? As its pre-release I can't install it by default 😢 

Thanks!

**Comment by jimasp** [comment]
Hi,

The plan is to get a proper release out in the next couple of months _if_ I can get enough time. (Before that happens, I have to get out a final pre-release first, as I want the code to be relatively stable/feature complete before first release version). 

In the meantime, I don't have any experience with devcontainers, but...

First, If you haven't already, I'd check that specifying a specific version in your json doesn't work? e.g. something like this:
`"extensions": ["jimasp.behave-vsc@0.4.0"]`
or maybe? this:
`"extensions": ["jimasp.behave-vsc@prerelease"]`

Assuming those fail, you can instead use the .vsix file and install that way.

This opens up a few options (these are all untested as I don't have a devcontainer to play with):

1. Use a `postCreateCommand` setting in your devcontainer json:
`code --install-extension jimasp.behave-vsc@prerelease`
(not sure about the context of this command of local vs remote, you might need something like ./.devcontainer/postCreateCommand.sh)

2. Use `dockerFile` setting in your devcontainer json and install however you like.

3. Use the "dev container CLI", possibly with your CI build.

4. Download locally, then install from a local disk
`curl https://marketplace.visualstudio.com/_apis/public/gallery/publishers/jimasp/vsextensions/behave-vsc/0.4.0/vspackage`
or
`curl https://github.com/jimasp/behave-vsc/releases/download/v0.4.0/behave-vsc-0.4.0.vsix"

add this to your devcontainer json
`"extensions": ["(vscode folder)/jimasp.behave-vsc.vsix"]`
(See [here](https://github.com/microsoft/vscode/issues/101654) for more on this last option)

**Comment by mike-oakley** [comment]
Ah nice one - adding @prerelease did it. I'll look forward to the initial release. Keep up the good work!
