### ISSUE TITLE
Support for Scenario Outline

### ISSUE THREAD

**Issue by schwaerz** [jimasp/behave-vsc#19]
**Is your feature request related to a problem? Please describe.**
Today I tried to use the Scenario Outline feature of behave. Unfortunately this does not *yet* seem to be supported by the plug-in. When trying to execute those parameterized tests, it will just hang. Also when scanning the available tests it would hang.

**Describe the solution you'd like**
Tests will be executed and each individual example's result will be shown as passed of failed

**Describe alternatives you've considered**
So far the only alternative would be to run behave manually from the command line - which of course I'd like to avoid since I found this nice plug-in 👍 

**Additional context**
Scenario outline example
```
    Scenario Outline: collect build writes build number <build number> into artifacts.properties
        Given CI environment variable is true
        And BUILD_NUMBER environment variable is <build number>
        When collect_build_info is called
        Then ~/.conan/artifacts.properties contains artifact_property_build.number=<build number>

        Examples:
            | build number |
            | 666          |
            | 999          |
```

Please let me know in case you need further information. I'd really love to see this plugin supporting that feature. Thanks!

**Comment by jimasp** [comment]
scenario outlines are supported.

however using parameters inside the scenario outline description was untested and i think that was probably causing your issue.

please update to release v0.4.1 and report back (or just close this issue if fixed).

**Comment by alexvaut** [comment]
I can confirm scenario with descriptions work for me

**Comment by jimasp** [comment]
Closed as no response from OP within 2 weeks. (Presumed fixed.)

**Comment by schwaerz** [comment]
Sorry for the late response, had some vacation. :)
And thanks for the quick fix 👍 , highly appreciated.
