### ISSUE TITLE
Bug in step detection

### ISSUE THREAD

**Issue by klausmyrseth** [jimasp/behave-vsc#26]
**Describe the bug (required):**
When defining steps for behave in python you define them in the features/steps directory, when I import behave and annotate:

import behave

@behave.given
def ...

This will not be detected as a step

while:
from behave import given

@given
def ...

Is detected

It would be nice if it supports the other scenario too, I was struggeling to get a proper experience of the product until I found that to be true.

**To Reproduce (required):**
See example above.

**Operating system (required):**
Running ubuntu latest lts with python 3.10

**Directory structure (optional, but often relevant):**
project/
- features/
- all feature definitions
---steps
---all step definitions in python

**Debug result (optional):**
result is you cant navigate to steps inside the editor if youre using the first methopd

**Comment by jimasp** [comment]
thanks for the bug report. 
fix applied in release v0.6.0.
