### ISSUE TITLE
Run/Debug config

### ISSUE THREAD

**Issue by pespinel** [jimasp/behave-vsc#33]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an interface for building custom runners, setting the feature/s to run, passing the parameters and so on ...

**Describe the solution you'd like**
Basically a copy of the run/degub configuration of Pycharm would be perfect

**Describe alternatives you've considered**
If this can't be done, We could add more configuration options to the plugin itself to add the working directory, add the content roots and the source roots to the PYTHONPATH.

**Additional context**
![Captura de pantalla 2023-08-01 a las 8 51 50](https://github.com/jimasp/behave-vsc/assets/37797002/a5165965-3275-4a5b-8ef7-3145187c6831)

**Comment by jimasp** [comment]
Completely custom configuration for running tools like behave is supplied out of the box by vscode, not by extensions.

For your screenshot example, I guess you would have something like this:
```
  {
        "name": "Recovery Password Feature",
        "type": "python",
        "request": "launch",
        "module": "behave",
        "console": "integratedTerminal",
        "args": [
            "no_login/recovery_password.feature",
            "-D",
            'TestExecution_language="o2uk_en-gb"',
        ]
    }
```

Completely untested, so it's probably wrong, but this should then appear with the name "Recovery Password Feature" in your run and debug dropdown.

There are some examples on stackoverflow here:
https://stackoverflow.com/questions/52725150/how-to-debug-behave-bdd-scenario-using-python-debugger-and-visual-studio-code
