### ISSUE TITLE
0.6.0 does not run a scenario if more than one scenario in a feture file and there are double quotes in the scenario title

### ISSUE THREAD

**Issue by chengwei45254** [jimasp/behave-vsc#34]
**Describe the bug (required):**

Behave-VSC 0.6.0 does not run a scenario under the following conditions:
1. There are more than one scenario in a feature file, and
2. One of the scenarios has double quotes in its title, and
3. That specific scenario, instead of the whole feature, is run from the Testing view

It looks like Behave-VSC 0.6.0 will skip the scenario, and the scenario test result icon in the Testing view will show a freezed, gray rotating icon. This issue did not happen in 0.5.0.

**To Reproduce (required):**

1. Write the following feature file tutorial.feature in "features" folder:
        
        Feature: showing off behave

          Scenario: run a "simple" test
            Given we have behave installed
            When we implement a simple test
            Then behave will test it for us!

          Scenario: run a difficult test
            Given we have behave installed
            When we implement a difficult test
            Then behave will test it for us!

2. Write the following step definition file tutorial.py in "features/steps" folder:

        from behave import *

        @given('we have behave installed')
        def step_impl(context):
            pass

        @when('we implement a simple test')
        def step_impl(context):
            assert True is not False

        @when('we implement a difficult test')
        def step_impl(context):
            assert True is not False

        @then('behave will test it for us!')
        def step_impl(context):
            assert context.failed is False        

4. From the Testing view, hover over the first scenario title 'run a "simple" test', and click "Run Test" button to run that specific scenario.
5. Check the Behave VSC output view, it shows that the scenario is skipped and is not run:

        --- BehaveVSC tests started for run 537333 @2023-09-05T06:03:09.811Z ---

        powershell commands:
        cd "c:\BehaveVSC"
        & "C:\Python311\python.exe" -m behave --show-skipped --junit --junit-directory "c:\Users\pdguser\AppData\Local\Temp\behave-vsc\junit\537333\BehaveVSC" -i "features/tutorial.feature$" -n "^run a "simple" test$"

        Feature: showing off behave # features/tutorial.feature:1

        0 features passed, 0 failed, 1 skipped
        0 scenarios passed, 0 failed, 2 skipped
        0 steps passed, 0 failed, 6 skipped, 0 undefined
        Took 0m0.000s

        --- BehaveVSC tests completed for run 537333 @2023-09-05T06:03:10.213Z (0.4024400999993086 secs)---    

6. From the Testing view, check the test result icon of that scenario. It displays a freezed, gray rotating icon.

**Operating system (required):**

Windows 10

**Directory structure (optional, but often relevant):**

        [BehaveVSC]
              [features]
                    [steps]
                         tutorial.py
                    tutorial.feature

**Screenshots and GIFS (optional):**

![behave-vsc-0 6 0-does-not-run-scenario](https://github.com/jimasp/behave-vsc/assets/47975135/dbdbdbe4-ecea-45af-bd27-1b13885e794d)

**Debug result (optional):**

N/A

**Pull request with proposed fix (optional):**

N/A

**Comment by jimasp** [comment]
thanks for the bug report.
this should be fixed in v0.6.1

**Comment by chengwei45254** [comment]
Thank you very much for making this good tool even better!
