### ISSUE TITLE
Configurable steps folder

### ISSUE THREAD

**Issue by kconkas** [jimasp/behave-vsc#37]
**Is your feature request related to a problem? Please describe.**
According to its documentation, behave allows flexibility in terms of [directory layout](https://behave.readthedocs.io/en/stable/gherkin.html#layout-variations). In particular, it doesn't require nesting of steps under feature files and allows these two folders to have the same parent - behave will search for step definitions recursively. This is the configuration I successfully used in several repositories and would like to retain.

**Describe the solution you'd like**
I would like to have a configurable option (similar to `behave-vsc.featuresPath`) to set the location of my step definitions (alternatively, for steps to be searched recursively from behave root, just the way behave does it).

**Describe alternatives you've considered**
I considered using a plugin called "Cucumber (Gherkin) Full Support".

**Additional context**

**Comment by jimasp** [comment]
>it doesn't require nesting of steps under feature files

neither does behave-vsc. 
do you mean under the features folder, rather than under feature files?

>behave will search for step definitions recursively

so does behave-vsc.
for example, you can have this structure where both steps folders will be found by recursion:

```
 . my-project
  .    +-- behave.ini
  .    +-- features/  
  .       +-- environment.py
  .       +-- steps/  
  .       |      +-- *.py  
  .       +-- storage_tests/  
  .       |      +-- *.feature  
  .       +-- web_tests/  
  .       |      +-- *.feature 
  .       |      +-- steps/
  .       |         +-- *.py    
```

can you give me an example of your desired directory structure?

**Comment by jimasp** [comment]
If I assume you have this structure:
```
tests
     +-- features
     +-- steps
```

then have you tried:

this in your `behave.ini`:
```
[behave]
paths = tests
```

along with this in your `.vscode/settings.json`:
```
"behave-vsc.featuresPath": "tests",
```

**Comment by kconkas** [comment]
@jimasp thanks for looking at this issue. What I meant was a folder structure like this:
```
 . my-project
 .    +-- behave.ini
 .    +-- features/  
 .    +-- steps/
```

**Comment by jimasp** [comment]
Also, I note from the behave page you linked:

_'the path to a features directory laid out as described above. It may be called anything but **MUST** contain at least one “name.feature” file **AND** a directory called “steps”. '_

**Comment by kconkas** [comment]
My `behave.ini` is as follows:
```
[behave]
paths=.
```

**Comment by kconkas** [comment]
@jimasp an example of a repository that works and uses this structure: https://github.com/sensynehealth/polaris-sms-api/tree/main/integration-tests

**Comment by jimasp** [comment]
ah, i needed the `environment.py` in the root of the project (i.e. as a sibling of the steps folder) instead of in the features folder.
so that makes it work for behave.
i'll take a look when i get some free time.

**Comment by jimasp** [comment]
please retest with release 0.6.3.
note that there is no setting for a configurable steps folder, because the steps folder is not configurable in behave.
however, it should detect the steps folder in the project root.

**Comment by jimasp** [comment]
0.6.4 has been released. hopefully this resolves.

**Comment by kconkas** [comment]
@jimasp thank you so much for your efforts on this feature. I tried to test it but it seems like my VSC can only see v0.3.1 as the latest pre-release version. Please see the attached video, in it 0.6.4 briefly flashes but then I end up installing 0.3.1 (which is 1 year old) even though "Marketplace Info" goes to show the latest update was on 2023/10/15. This may be something to do with my VSC configuration but googling didn't produce any useful results. VSC 1.67.2 on macOS Ventura 13.5.

https://github.com/jimasp/behave-vsc/assets/8178837/b29e3de4-3801-43c1-82a9-8af5c0f656fe

**Comment by kconkas** [comment]
@jimasp installing the latest VSC 1.83.1 addressed the above issue. I can now resolve steps except for the ones using regexps (but that was never advertised as working in behave-vsc so I suppose that hasn't been implemented yet). Thanks again for your work on this extension. I look forward to seeing future updates. Please feel free to close this ticket now.

**Comment by jimasp** [comment]
>I tried to test it but it seems like my VSC can only see v0.3.1 as the latest pre-release version.

yes this is because different versions of the extension are tested against different vscode versions, and may not work with older versions. so extension versions are tied to the vscode version i tested against. 
the vscode version that was used for testing can be found in the release notes.
