### ISSUE TITLE
Add ability to change CWD

### ISSUE THREAD

**Issue by konradzagozda** [jimasp/behave-vsc#39]
**Is your feature request related to a problem? Please describe.**

Project directory structure looks like this:

automation-tests
  selenium-aws
  └── tests
      ├── __init__.py
      ├── behave-parallel.py
      ├── drag_and_drop.js
      ├── driver
      ├── example_files
      ├── features
      └── utils

changing features path is not enough, because project imports use `from features... import ...` and it breaks things, changing CWD fixes the issue.

**Describe the solution you'd like**
I'd like to point to selenium-aws/tests as entry point for behave, e.g. with configuration setting like: `behave-vsc.cwd` or `behave-vsc.entryPoint` 

**Describe alternatives you've considered**
As a workaround I can open project in tests directory and select interpreter from 2 directories up or include venv in tests dir. But I lose visibility to rest of the project.

**Comment by jimasp** [comment]
it's hard for me to understand this setup without knowing where all the feature files and step files are.

i think you're saying that this works on the command line:
```
cd selenium-aws/tests
python -m behave
```

that being the case, presumably you have `.feature` files inside the `tests` folder?
and you don't want to run the feature files in `features`, you want to run the feature files in `tests`
and you have a `steps` folder inside `tests` that imports from python files inside `features`?

Regarding: "As a workaround I can open project in tests directory and select interpreter from 2 directories up or include venv in tests dir. But I lose visibility to rest of the project."

Have you tried using a [multiroot workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces) so you have two different views on the same project?

**Comment by jimasp** [comment]
so for example with multiroot, you could add the folder selenium-aws as one of the root folders

**Comment by jimasp** [comment]
each workspace root can have its own settings for the interpreter etc.

**Comment by jimasp** [comment]
alternatively i guess your command line might look like this?
```
cd selenium-aws/tests
python -m behave ../features
```

**Comment by jimasp** [comment]
re. "project imports use from features... import ... and it breaks things" - i would have thought this would be fixable with a `PYTHONPATH` environment variable? (you can set this via a `.env` file in your project folder, or via behave-vsc.envVarOverrides` if you only want the pythonpath to be apply when the extension is running behave tests.)

note that as far as the extension goes, it is not as simple as providing a setting to change behave's working directory because there are lots of relative paths to consider in the extension code that would be affected.

if none of the above suggestions help, then please note that i cannot progress this issue unless you can supply:
a) an example public repository that creates the issue, and
b) the commands that you use for that repo to successfully run your tests outside of vscode (i.e. the `cd` and `python -m behave` commands).

**Comment by davemcbride** [comment]
I believe I have the same issue/request. Firstly I get a lot of help from your extension so thank you, and I'm bound by a directory structure someone else has setup which isn't easily changeable.

```
Workspace: test_automation_v2.0
Local path: /home/dave/git/test_automation/test_automation_v2.0

# Directory structure within workspace
.vscode
.behaverc
aws
bdd
├── features
└── utilities
```
After adding `.vscode/settings.json` and `.behaverc` to the root directory as below behave can find the features folder
```
#.vscode/settings.json
{
    "behave-vsc.featuresPath": "BDD/features"
}

# .behaverc
[behave]
paths=BDD/features
```
However environment.py imports some local modules e.g. 
`from utilities.getTestEnvironmentData import *`

and the relative path is wrong so:
```
  File "BDD/features/environment.py", line 1, in <module>
    from utilities.getTestEnvironmentData import *
ModuleNotFoundError: No module named 'utilities'
Exception ModuleNotFoundError: No module named 'utilities'
```
The commands `behave-vsc` runs are:
```
cd "/home/dave/git/test_automation/test_automation_v2.0"
"/home/dave/.virtualenvs/test_automation/bin/python" -m behave -i "BDD/features/test.feature$" --show-skipped --junit --junit-directory "/tmp/behave-vsc/junit/408845/test_automation_v2.0"
```
To respect the relative paths in `environment.py` the `cd` command would need to be
```
cd "/home/dave/git/test_automation/test_automation_v2.0/BDD"
instead of
cd "/home/dave/git/test_automation/test_automation_v2.0"
```

Hence (I believe) @konradzagozda 's request for `behave-vsc.cwd` or `behave-vsc.entryPoint` for a config to change the working directory.

**Comment by jimasp** [comment]
@davemcbride 
relative import problems are normally fixable with the `PYTHONPATH` environment variable.
behave-vsc provides the facility to temporarily override env vars (i.e. during behave runs) via the `behave-vsc.envVarOverrides` setting.

if i assume your project looks like this:

```
.vscode
.behaverc (contents: [behave]\n paths=BDD/features)
aws
BDD
├── features
    └── steps
        └── my_steps.py
    ├── environment.py  (contents: from utilities.getTestEnvironmentData import *\n some_func())
    ├── my.feature        
└── utilities
    ├──  __init__.py
    ├──  getTestEnvironmentData.py  (contents: def some_func():\n pass)
```


then i would expect something like this to work in `.vscode/settings.json`

```
  "behave-vsc.envVarOverrides": {
      "PYTHONPATH": "BDD"
  },
```

**Comment by jimasp** [comment]
previous comment edited

**Comment by davemcbride** [comment]
That worked!
Thanks very much!

**Comment by jimasp** [comment]
closing this issue as no response by OP @konradzagozda after 3 weeks. 
presumed fixed by OP using `behave-vsc.envVarOverrides` to set `PYTHONPATH`.
