### ISSUE TITLE
[Feature request] Setting breakpoints at the steps in the feature files

### ISSUE THREAD

**Issue by chengwei45254** [jimasp/behave-vsc#45]
Currently, we can set breakpoints at step definition (implementation) files. Is it possible that we can also set breakpoints directly at the steps in the feature files?

![image](https://github.com/jimasp/behave-vsc/assets/47975135/cdfd9107-e47e-454c-affb-76de46b24cb6)

![image](https://github.com/jimasp/behave-vsc/assets/47975135/4e00a037-bfc6-4b6a-970a-9762e080a0ea)

With this feature, we can trace the test execution from the very beginning of each step description. This will help us grab the test flow more clearly when debugging.

Thank you very much!

**Comment by jimasp** [comment]
This isn't possible.
The extension does not implement it's own debugger, it uses Microsoft's Python extension debugger.
The Microsoft debugger only understands the Python language, it does not understand Gherkin.

**Comment by chengwei45254** [comment]
Understood. Thanks for explanation.

p.s. I asked this feature because a C# BDD framework "SpecFlow" supports it (
https://docs.specflow.org/projects/specflow/en/latest/Execution/Debugging.html).
I thought maybe it is also doable here.
